# default command type
command_type: system

# run the same task in the previous revision if the current task fails
stepback: true

functions:

  "fetch source" :
    - command: git.get_project
      params:
        directory: gopath/src/github.com/10gen

  "setup gopath" :
    - command: shell.exec
      params:
        silent: false
        script: |
            set -x
            set -v
            export GOPATH=gopath
            ${gorootvars} go get github.com/spacemonkeygo/spacelog
            mkdir -p gopath/src/github.com/10gen
            exit 0

  "go test" :
    - command: shell.exec
      type: test
      params:
        script: |
            set -x
            set -v
            set -e
            export GOPATH=gopath
            ${gorootvars} go test ${args} -tags '${build_tags}' -v

post:
  - command: shell.exec
    params:
      silent: true
      script: |
        set -x
        set -v
        rm -rf gopath
        exit 0

tasks:

- name: "test"
  commands:
  - func: "setup gopath"
  - func: "fetch source"
  - func: "go test"

buildvariants:

#######################################
#           macOS Buildvariant        #
#######################################

- name: macOS-1012
  display_name: MacOS 10.12
  run_on:
  - macos-1012
  expansions:
    gorootvars: CGO_CPPFLAGS=-I/opt/mongodbtoolchain/v2/include CGO_CFLAGS=-mmacosx-version-min=10.10 CGO_LDFLAGS=-mmacosx-version-min=10.10
    build_tags: "openssl_pre_1.0"
  tasks:
  - name: test

#######################################
#     RHEL Buildvariants              #
#######################################

- name: rhel70
  display_name: RHEL 7.0
  run_on:
  - rhel70
  expansions:
    gorootvars: PATH="/opt/go/bin:$PATH"
    build_tags: ""
  tasks:
  - name: test

#######################################
#          Ubuntu Buildvariants       #
#######################################

- name: ubuntu1604
  display_name: Ubuntu 16.04
  run_on:
  - ubuntu1604-test
  expansions:
    build_tags: ""
  tasks:
  - name: test

#######################################
#        Windows Buildvariants        #
#######################################

- name: windows-64
  display_name: Windows 64-bit
  run_on:
  - windows-64-vs2013-test
  expansions:
    build_tags: ""
  tasks:
  - name: test
