stepback: true
command_type: system
buildvariants:
- name: build
  display_name: Windows_64
  run_on:
  - windows-64-vs2013-compile
  tasks:
    - name: "build32"
    - name: "build64"

pre:
  - func: "fetch source"

post:
  - func: "upload artifacts"

tasks:

- name: build32
  exec_timeout_secs: 14400 # 4h
  commands: 
     - func: "build32"

- name: build64
  exec_timeout_secs: 14400 # 4h
  commands: 
     - func: "build64"


- name: compile
  exec_timeout_secs: 14400 # 4h
  commands:
    - func: "install dependencies"
    - func: "build mongosql_auth"
      vars:
        release: true
    - func: "create packages"
    - func: "upload packages"

- name: sign
  depends_on:
    - name: compile
  commands:
    - func: "fetch packages"
    - func: "sign msi installer"
    - func: "upload release packages"

- name: unit_tests
  exec_timeout_secs: 14400 # 4h
  commands:
    - func: "install dependencies"
    - func: "build mongosql_auth"
    - func: "run unit tests"

- name: integration_tests_plain
  exec_timeout_secs: 14400 # 4h
  commands:
    - func: "install dependencies"
    - func: "start mongosqld"
      vars:
        mongodb_args: --mongo-uri=ldaptest.10gen.cc
    - func: "build mongosql_auth"
    - func: "run plain integration tests"

- name: integration_tests_scram
  exec_timeout_secs: 14400 # 4h
  commands:
    - func: "install dependencies"
    - func: "start mongosqld"
    - func: "start mongo-orchestration"
    - func: "build mongosql_auth"
    - func: "run scram integration tests"

- name: integration_tests_gssapi
  exec_timeout_secs: 14400 # 4h
  commands:
    - func: "install dependencies"
    - func: "build mongosql_auth"
    - func: "run gssapi integration tests"

functions:
  "build32":
    command: shell.exec
    type: test
    params:
      script: |
          ./odbc/bin/win32_odbc_build.sh

  "build64":
    command: shell.exec
    type: test
    params:
      script: |
          ./odbc/bin/win64_odbc_build.sh

  "build mongosql_auth":
    command: shell.exec
    type: test
    params:
      script: |
          ${PREPARE_SHELL}
          export RELEASE='${release}'
          ${SCRIPT_DIR}/build-mongosql-auth.sh

  "create packages":
    command: shell.exec
    type: test
    params:
      script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/create-packages.sh

  "export variables":
    - command: shell.exec
      params:
        silent: true
        working_dir: odbc
        script: |
          if [ "Windows_NT" = "$OS" ]; then
              set -o igncr
          fi

          VARIANT="${variant|other}"

          export PROJECT_DIR="$(pwd)"
          export SCRIPT_DIR="$PROJECT_DIR/test/bin"
          if [ "Windows_NT" = "$OS" ]; then
              export PROJECT_DIR="$(cygpath -m $PROJECT_DIR)"
              export SCRIPT_DIR="$(cygpath -m $SCRIPT_DIR)"
          fi

          CURRENT_VERSION="$(git describe --always)"

          . "$SCRIPT_DIR/platforms.sh"

          # create expansions from values calculated above
          cat <<EOT > $PROJECT_DIR/expansions.yml
          PROJECT_DIR: "$PROJECT_DIR"
          SCRIPT_DIR: "$SCRIPT_DIR"
          CURRENT_VERSION: "$CURRENT_VERSION"
          PUSH_NAME: "$PUSH_NAME"
          PUSH_ARCH: "$PUSH_ARCH"
          PREPARE_SHELL: |
             if [ "Windows_NT" = "$OS" ]; then
                 set -o igncr
                 export SHELLOPTS
             fi
             export VARIANT="$VARIANT"
             export PROJECT_DIR="$PROJECT_DIR"
          EOT
    - command: expansions.update
      params:
        file: odbc/expansions.yml

  "fetch packages":
    - command: s3.get
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        remote_file: odbc/artifacts/${version_id}/${build_variant}/pkg/release-bundles.tgz
        extract_to: odbc/test/artifacts/
        bucket: mciuploads

  "fetch source":
    - command: shell.exec
      params:
        silent: true
        script: |
          rm -rf odbc
    - command: git.get_project
      params:
        directory: odbc
    - command: git.apply_patch
      type: test
      params:
        directory: odbc

  "install dependencies":
    command: shell.exec
    params:
      script: |
        ${PREPARE_SHELL}
        ${SCRIPT_DIR}/install-build-deps.sh

  "reset testing state":
    - command: shell.exec
      params:
        silent: true
        script: |
          ${killall_mci}
    - command: shell.exec
      params:
        script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/reset-testing-state.sh

  "run plain integration tests":
    - command: shell.exec
      type: test
      params:
        script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/run-integration-tests-plain.sh

  "run scram integration tests":
    - command: shell.exec
      type: test
      params:
        script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/run-integration-tests-scram.sh

  "run gssapi integration tests":
    - command: shell.exec
      type: test
      params:
        script: |
          ${PREPARE_SHELL}
          export GSSAPI_USER=${gssapi_auth_linux_user}
          export GSSAPI_PASSWD=${gssapi_auth_linux_password}
          export GSSAPI_KTNAME=${PROJECT_DIR}/test/artifacts/gssapi/drivers.keytab
          echo "${gssapi_auth_linux_keytab_base64}" > /tmp/drivers.keytab.base64
          mkdir -p $(dirname $GSSAPI_KTNAME)
          base64 --decode /tmp/drivers.keytab.base64 > $GSSAPI_KTNAME
          ${SCRIPT_DIR}/run-integration-tests-gssapi.sh

  "run unit tests":
    - command: shell.exec
      type: test
      params:
        script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/run-unit-tests.sh

  "sign msi installer":
    - command: shell.exec
      params:
        silent: true
        script: |
          echo "${signing_token_bi_connector}" > ${PROJECT_DIR}/signing_auth_token
    - command: shell.exec
      params:
        working_dir: odbc/test/artifacts
        script: |
          /usr/local/bin/notary-client.py \
              --key-name "bi-connector" \
              --auth-token-file ${PROJECT_DIR}/signing_auth_token \
              --comment "Evergreen Automatic Signing (odbc) - ${version_id} - ${build_variant}" \
              --notary-url http://notary-service.build.10gen.cc:5000 \
              --skip-missing \
              release.msi

  "start mongo-orchestration":
    - command: shell.exec
      params:
        script: |
          ${PREPARE_SHELL}
          ${SCRIPT_DIR}/start-orchestration.sh

  "start mongosqld":
    - command: shell.exec
      params:
        script: |
          ${PREPARE_SHELL}
          export EVG_USER=${evg_user}
          export EVG_KEY=${evg_key}
          export AWS_ACCESS_KEY_ID=${aws_key}
          export AWS_SECRET_ACCESS_KEY=${aws_secret}
          export SQLPROXY_MONGO_ARGS=${mongodb_args}
          ${SCRIPT_DIR}/start-sqlproxy.sh

  "upload artifacts":
    - command: s3.put
      params:
        optional: true
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/build-win32/odbc.msi
        remote_file: mongo-odbc-driver/artifacts/${build_variant}/${task_id}/mongo-odbc-win32.msi
        content_type: application/x-msi
        bucket: mciuploads
        permissions: public-read
        display_name: "mongo-odbc-win32.msi"
    - command: s3.put
      params:
        optional: true
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/build-win64/odbc.msi
        remote_file: mongo-odbc-driver/artifacts/${build_variant}/${task_id}/mongo-odbc-win64.msi
        content_type: application/x-msi
        bucket: mciuploads
        permissions: public-read
        display_name: "mongo-odbc-win64.msi"


  "upload packages":
    - command: archive.targz_pack
      params:
        target: odbc/test/artifacts/upload.tgz
        source_dir: odbc/test/artifacts/
        include:
          - "./release.*"
    - command: s3.put
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/test/artifacts/upload.tgz
        remote_file: odbc/artifacts/${version_id}/${build_variant}/pkg/release-bundles.tgz
        content_type: application/x-gzip
        bucket: mciuploads
        permissions: public-read
        display_name: All Release Bundles (.tgz)

  "upload release packages":
    - command: s3.put
      params:
        optional: true
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/test/artifacts/release.tgz
        remote_file: odbc/artifacts/${build_variant}/${task_id}/mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.tgz
        content_type: application/x-gzip
        bucket: mciuploads
        permissions: public-read
        display_name: mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.tgz
    - command: s3.put
      params:
        optional: true
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/test/artifacts/release.zip
        remote_file: odbc/artifacts/${build_variant}/${task_id}/mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.zip
        content_type: application/x-gzip
        bucket: mciuploads
        permissions: public-read
        display_name: mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.zip
    - command: s3.put
      params:
        optional: true
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: odbc/test/artifacts/release-signed.msi
        remote_file: odbc/artifacts/${build_variant}/${task_id}/mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.msi
        content_type: application/x-msi
        bucket: mciuploads
        permissions: public-read
        display_name: mongosql-auth-${PUSH_NAME}-${PUSH_ARCH}-${CURRENT_VERSION}.msi

axes:

- id: os
  display_name: OS
  values:
  - id: ubuntu1404-64
    display_name: Ubuntu 14.04
    run_on: ubuntu1404-build
    variables:
      variant: ubuntu1404-64
  - id: rhel70
    display_name: RHEL 7.0
    variables:
      variant: rhel70
    run_on: rhel70
  - id: osx
    display_name: OSX 10.12
    run_on: macos-1012
    variables:
      variant: macos
  - id: windows-vs2013
    display_name: Windows 64 (VS2013)
    run_on: windows-64-vs2013-compile
    variables:
      variant: windows-vs2013
  - id: windows-32
    display_name: Windows 32 (VS2013)
    run_on: windows-64-vs2013-compile
    variables:
      variant: windows-32

- id: os-disabled
  display_name: Disabled OSes
  values:
  - id: debian71
    display_name: Debian 7.1
    run_on: debian71-test
    variables:
      variant: debian71
  - id: debian81
    display_name: Debian 8.1 (nightly)
    run_on: debian81-test
    variables:
      variant: debian81
  - id: linux-64-amazon-ami
    display_name: Amazon Linux (Enterprise)
    variables:
      variant: amazon
    run_on: linux-64-amzn-build
  - id: rhel62
    display_name: RHEL 6.2
    variables:
      variant: rhel62
    run_on: rhel62-test
  - id: rhel-71-ppc64le
    display_name: RHEL 7.1 PPC64LE
    variables:
      variant: rhel71-ppc
    run_on: rhel71-power8-test
    batchtime: 1440 # 1 day
  - id: rhel-72-s390x
    display_name: RHEL 7.2 s390x (nightly)
    variables:
      variant: rhel72-s390x
    run_on:
    - rhel72-zseries-build
    - rhel72-zseries-test
    batchtime: 1440 # 1 day
  - id: suse11-64
    display_name: SLES 11
    variables:
      variant: suse11
    run_on: suse11-test
  - id: suse12-64
    display_name: SLES 12
    variables:
      variant: suse12
    run_on: suse12-test

